name: skill_pathway_app
description: "A new Flutter project for Skill Pathway Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

  # State Management & Network
  provider: ^6.1.1
  dio: ^5.4.0
  supabase_flutter: ^2.3.4  # Auth & Supabase Services

  # UI Icons & Styling
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true